services:
  music-bot:
    build: .
    container_name: outa-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1024M
